import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { InitalPage } from "@/components/inital-page";
import { Header } from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <div className="flex">
          <Header />
          {/* <div className="flex items-center justify-center flex-grow">
            {children}
          </div> */}

          {children}
        </div>
      </body>
    </html>
  );
}
